blank_issues_enabled: false
contact_links:
  - name:  ğŸ™ Ask a question
    url: https://github.com/PatrickF1/fzf.fish/discussions/new?category=q-a
    about: Get help with using the plugin
  - name: ğŸ’¡ Idea
    url: https://github.com/PatrickF1/fzf.fish/discussions/new?category=ideas
    about: Suggest a new feature or an improvement to existing features
